version: 2.1
jobs:
  build:
    docker:
      - image: jesperancinha/je-all-build:0.0.1

    working_directory: /home/test/repo

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Build Test and Install
          command: mvn clean install

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run:
          name: Integration tests
          command: mvn integration-test